import { chromium } from "playwright";
import { virtualAuthenticator, signUp } from "./auth";
const out = process.argv[2];
const b = await chromium.launch();
const page = await (await b.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 })).newPage();
page.on("pageerror", (e) => console.log("[pageerror]", e.message));
page.on("console", (m) => m.type() === "error" && !m.text().includes("404") && console.log("[console]", m.text().slice(0, 300)));
await virtualAuthenticator(page);
await signUp(page, "Mary Jackson");
await page.getByTestId("example-flange").click();
await page.waitForURL(/\/d\//);
await page.waitForFunction(() => (globalThis as any).__ws?.results?.flange && (globalThis as any).__ws.kernelReady, null, { timeout: 30000 });
await page.getByRole("tab", { name: "Params" }).click();
const f = page.getByTestId("params-panel").getByRole("spinbutton").nth(3); // hubHeight
await f.click(); await f.fill("30"); await f.press("Enter");
await page.waitForFunction(() => (globalThis as any).__ws.versions.length >= 2, null, { timeout: 20000 });
await page.waitForTimeout(1500);
await page.getByRole("tab", { name: "History" }).click();
console.log("versions", await page.getByTestId("version-row").count());
await page.evaluate(() => (globalThis as any).__cmp.open());
await page.waitForTimeout(2500);
console.log("compare", await page.evaluate(() => JSON.stringify({ against: (globalThis as any).__cmp.against, err: (globalThis as any).__cmp.error })));
await page.screenshot({ path: `${out}/compare.png` });
await page.keyboard.down("b"); await page.waitForTimeout(150);
await page.screenshot({ path: `${out}/compare-b.png` });
await page.keyboard.up("b");
await page.evaluate(() => (globalThis as any).__cmp.close());
await page.getByTestId("version-row").last().click();
await page.waitForTimeout(2500);
await page.screenshot({ path: `${out}/viewing.png` });
await page.getByTestId("restore-version").click();
await page.waitForTimeout(3000);
console.log("after restore", await page.evaluate(() => JSON.stringify({ n: (globalThis as any).__ws.versions.length, msg: (globalThis as any).__ws.versions[0].message })));
await b.close();
