import { chromium } from "playwright";
import { virtualAuthenticator, signUp } from "./auth";
const out = process.argv[2];
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
page.on("console", (m) => m.type() === "error" && console.log("[console]", m.text()));
page.on("pageerror", (e) => console.log("[pageerror]", e.message));
await virtualAuthenticator(page);
await page.goto("http://localhost:5173/signin");
await page.screenshot({ path: `${out}/signin.png` });
await signUp(page, "Ada Lovelace");
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/docs.png` });
await page.getByTestId("example-bracket").click();
await page.waitForURL(/\/d\//);
await page.waitForFunction(() => (globalThis as any).__ws?.results?.bracket, null, { timeout: 30000 }).catch(() => console.log("no result"));
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/workspace.png` });
console.log(await page.evaluate(() => JSON.stringify({ k: (globalThis as any).__ws?.kernelReady, e: (globalThis as any).__ws?.engineError, parts: (globalThis as any).__ws?.parts, res: Object.keys((globalThis as any).__ws?.results ?? {}) })));
await b.close();
