import { chromium } from "playwright";
import { virtualAuthenticator, signUp } from "./auth";
const out = process.argv[2];
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
page.on("pageerror", (e) => console.log("[pageerror]", e.message));
page.on("console", (m) => m.type() === "error" && !m.text().includes("404") && console.log("[console]", m.text().slice(0, 300)));
await virtualAuthenticator(page);
await signUp(page, "Grace Hopper");
await page.getByTestId("example-flange").click();
await page.waitForURL(/\/d\//);
await page.waitForFunction(() => (globalThis as any).__ws?.results?.flange && (globalThis as any).__ws.kernelReady, null, { timeout: 30000 });
await page.waitForTimeout(800);
const vp = await page.getByTestId("viewport").boundingBox();
// click a face near the center
await page.mouse.move(vp!.x + vp!.width * 0.5, vp!.y + vp!.height * 0.42);
await page.waitForTimeout(100);
await page.mouse.click(vp!.x + vp!.width * 0.5, vp!.y + vp!.height * 0.42);
await page.waitForTimeout(600);
console.log("sel", await page.evaluate(() => JSON.stringify((globalThis as any).__ws.selection)));
console.log("name", await page.getByTestId("stable-name").textContent().catch(() => null));
await page.screenshot({ path: `${out}/ws-select.png` });
await page.getByRole("tab", { name: "Params" }).click();
await page.waitForTimeout(300);
await page.screenshot({ path: `${out}/ws-params.png` });
// type into thickness field
const field = page.getByTestId("params-panel").locator("input").nth(2);
await field.click(); await field.fill("12"); await field.press("Enter");
await page.waitForTimeout(2500);
console.log("cfg", await page.evaluate(() => JSON.stringify({ active: (globalThis as any).__ws.activeConfigID, params: (globalThis as any).__ws.results.flange.params.map((p: any) => [p.name, p.value, p.overridden]) })));
await page.screenshot({ path: `${out}/ws-params2.png` });
console.log("stack", await page.evaluate(() => JSON.stringify((globalThis as any).__ws.undoStack.map((u: any) => [u.label, u.undo.map((m: any) => m.name ?? Object.keys(m))]))));
console.log("active", await page.evaluate(() => document.activeElement?.tagName + " " + navigator.platform));
await page.keyboard.press("Meta+z"); await page.waitForTimeout(2000);
console.log("stack after key", await page.evaluate(() => (globalThis as any).__ws.undoStack.length));
console.log("undo()", await page.evaluate(async () => { const r = await (globalThis as any).__ws.undo(); await new Promise((f) => setTimeout(f, 2000)); return r + " " + JSON.stringify((globalThis as any).__ws.activeConfig?.overrides?.map((o: any) => o.name)); }));
console.log("after undo", await page.evaluate(() => JSON.stringify((globalThis as any).__ws.results.flange.params.map((p: any) => [p.name, p.value, p.overridden]))));
await b.close();
