// Embeds packages/sync/migrations/*.sql into a module, so a bundled server (adapter-bun build,
// Docker image) doesn't need the .sql files on disk. Rerun after adding a migration; a unit test
// fails if the embedded copy drifts from the files.
import { readdir } from "node:fs/promises";
import { join } from "node:path";

const dir = join(import.meta.dir, "../packages/sync/migrations");
const files = (await readdir(dir)).filter((f) => f.endsWith(".sql")).sort();
const entries = await Promise.all(files.map(async (f) => [f, await Bun.file(join(dir, f)).text()] as const));
const out = `// Generated by scripts/gen-migrations.ts from packages/sync/migrations. Do not edit.
export const MIGRATIONS: readonly (readonly [name: string, sql: string])[] = ${JSON.stringify(entries, null, 1)};
`;
await Bun.write(join(import.meta.dir, "../packages/sync/src/server/migrations.gen.ts"), out);
console.log(`embedded ${files.length} migrations`);
