// Generates packages/mcp/src/resources.ts: the modeling API's .d.ts (from packages/api, with doc
// comments) and the example parts, served to agents as MCP resources (§5 Designed for agents).
import { $ } from "bun";
import { Glob } from "bun";
import { join } from "node:path";
import { readFileSync, writeFileSync, rmSync, mkdirSync } from "node:fs";

const root = join(import.meta.dir, "..");
const out = join(root, ".data/api-dts");
rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
await $`bunx tsc ${join(root, "packages/api/src/index.ts")} --declaration --emitDeclarationOnly --stripInternal --outDir ${out} --skipLibCheck --target ES2022 --module ESNext --moduleResolution Bundler --strict --lib ES2022,DOM --types bun`.quiet().nothrow();
const files = ["index", "part", "assembly", "connector", "sketch", "path3d", "solid", "selection", "plane", "units", "types", "std/index", "std/parts", "std/holes", "std/tables"];
let dts = `// The \`parasocial\` module studio scripts import. Generated from packages/api (doc comments included).\n`;
for (const f of files) {
  const p = [...new Glob(`**/${f}.d.ts`).scanSync(out)].sort((a, b) => a.length - b.length)[0];
  if (!p) continue;
  dts += `\n// ───── ${f}.ts ─────\n` + readFileSync(join(out, p), "utf8").replace(/^import .*$/gm, "").replace(/^export \{\};$/gm, "");
}
let ex = "# Example parts\n\nReal scripts from Parasocial's example documents.\n";
for (const f of [...new Glob("*/{studios,lib}/*.ts").scanSync(join(root, "examples"))].sort()) ex += `\n## examples/${f}\n\n\`\`\`ts\n${readFileSync(join(root, "examples", f), "utf8").trim()}\n\`\`\`\n`;
writeFileSync(join(root, "packages/mcp/src/resources.ts"), `// Generated by scripts/gen-mcp-resources.ts — do not edit.\nexport const API_DTS = ${JSON.stringify(dts)};\nexport const EXAMPLES = ${JSON.stringify(ex)};\n`);
console.log(`api d.ts ${dts.length} chars, examples ${ex.length} chars`);
