// The `parasocial` module that studio scripts import. Everything here is frozen by the runtime.
export { part, param } from "./part";
export type { PartDef, PartTools, ParamOptions, ConnectorRef } from "./part";
export { assembly } from "./assembly";
export type { AssemblyDef, AssemblyTools, JointAt, JointOpts, MateOpts, Range, Instance, SubAssembly, Body, InsertOpts, Placement } from "./assembly";
export type { FrameSpec } from "./connector";
export { sketch, Sketch, loft, pipe } from "./sketch";
export type { P2, ExtrudeOpts, RevolveOpts } from "./sketch";
export type { SweepOpts, PipeOpts } from "./sketch";
export { path3d, helix, Path3d } from "./path3d";
export type { HelixOpts } from "./path3d";
export { Solid, box, cylinder, thicken, MATERIALS } from "./solid";
export { measure, check } from "./measure";
export type { Measurable, BoundingBox, Closest } from "./measure";
export { EntitySet } from "./selection";
export type { Entity, OpRef } from "./selection";
export type { SelectOpts } from "./solid";
export { plane, Plane } from "./plane";
export type { AxisLike } from "./plane";
export { mm, cm, m, inch, ft, deg, rad, evaluate } from "./units";
export type { Unit } from "./units";
export type { Appearance } from "./types";
export type { Vec3 } from "@parasocial/kernel";
